### ISSUE TITLE
Add OAuth Provider Login to Template

### ISSUE THREAD

**Issue by 0xDeadcell** [Atticuszz/fastapi_supabase_template#1]
Hi,

Adding an optional OAuth Provider Login to the would be great, as you wouldn't have to store the password yourself and deal with the security concerns of it. Instead it might be better to optionally allow an OAuth provider (e.g., google, github) and store the auth/session token thru the database for future checks to see if a user is logged in.

**Comment by Atticuszz** [comment]
thanks bro for your generous suggesttions😄，i do agree that，and plan to do it within weeks，if u like we can work together for it🥰

**Comment by Atticuszz** [comment]
the new commit have the function thatyou love，try it😁

**Comment by Atticuszz** [comment]
in supabase async py resp

**Comment by Atticuszz** [comment]
> Hi,
> 
> Adding an optional OAuth Provider Login to the would be great, as you wouldn't have to store the password yourself and deal with the security concerns of it. Instead it might be better to optionally allow an OAuth provider (e.g., google, github) and store the auth/session token thru the database for future checks to see if a user is logged in.

good question，i tried to achieve it for a couple of weeks，but finally，i think the auth should be handled by supabase-js，fastapi only pays attention on access token to get who send the request
