### ISSUE TITLE
When shall we expect complete supabase-py adoption istead of supabase_py_async ?

### ISSUE THREAD

**Issue by riyazsarah** [Atticuszz/fastapi_supabase_template#138]
**Is your feature request related to a problem? Please describe.**
We wanted to use single module to work instead of getting limited with supabase_py_async

**Describe the solution you'd like**
Can we refactor this code to accomodate supabase-py ?

**Describe alternatives you've considered**
No

**Additional context**

**Comment by Atticuszz** [comment]
> Can we refactor this code to accomodate supabase-py ?
yes we will do it later! you can make a new PR which it do help!

**Comment by Atticuszz** [comment]
it fixed in #139

**Comment by riyazsarah** [comment]
Thanks a Ton. Really aprpeciate your quick work here
