### ISSUE TITLE
How i access my docs as superuser???

### ISSUE THREAD

**Issue by MaHDiaLaGaB** [Atticuszz/fastapi_supabase_template#141]
I am running the system but when i go to /docs and i need to try the endpoints i need to add O2auth it's written:
**Token URL: please login by supabase-js to get token**
how i do that? if i uncomment the lines:
```
await super_client.auth.sign_in_with_password(
    {"email": settings.SUPERUSER_EMAIL, "password": settings.SUPERUSER_PASSWORD}
    )
```
i got error await can't be used with None Type

**Comment by Atticuszz** [comment]
1. did you mean that do not understand how to test endpoint with \doc manually?

2. token are captured by endpoint dependency automatically 

3. what's kind of token did you use?

4. more code examples or your repo?

**Comment by Atticuszz** [comment]
1. the token which captured by dependency is the **user's access_token**, so i thinks we can test it in `docs` after sign in manually with `super_client.auth.sign_in_with_password`
```python
response = await db_client.auth.sign_up(
        {"email": fake_email, "password": fake_password}
    )
    assert response.session.access_token is not None
```
the `response.session.access_token` is the token dependency love,which it may work in `doc`

2. the `doc` form looks wired

**Comment by MaHDiaLaGaB** [comment]
Thank you so much,
