### ISSUE TITLE
Authentication Issues

### ISSUE THREAD

**Issue by noamsiegel** [Atticuszz/fastapi_supabase_template#80]
**Describe the bug**
Even with exporting all the correct keys, I still get "Detail: Not Authenticated"

**To Reproduce**

1. Follow all the README.md steps
2. export keys

**Expected behavior**
I expect the FastAPI endpoints to work.

**Screenshots**
![image](https://github.com/noamsiegel/Webapp/assets/52804845/8658f1e8-e534-4286-a127-f3cf29a2c805)
![image](https://github.com/noamsiegel/Webapp/assets/52804845/2d6d117e-315b-4665-8589-f7ef5d99edf0)

**Desktop (please complete the following information):**
- OS: MacOS 14.2.1 (23C71)
- Browser: Chrome 123.0.6312.59

**Comment by Atticuszz** [comment]
Hi,

I noticed the images aren't showing up for me. Could you please update the image links? It would really help me follow along better.

Thanks!
